### ISSUE TITLE
NPE when calling org.glassfish.grizzly.servlet.HttpServletRequestImpl.getRemoteHost

### ISSUE THREAD

**Issue by zolyfarkas** [eclipse-ee4j/glassfish-grizzly#2042]
Exception detail:

```
Caused by: java.lang.NullPointerException
	at org.glassfish.grizzly.http.HttpRequestPacket.remoteHost(HttpRequestPacket.java:336)
	at org.glassfish.grizzly.http.HttpRequestPacket.getRemoteHost(HttpRequestPacket.java:362)
	at org.glassfish.grizzly.http.server.Request.getRemoteHost(Request.java:1227)
	at org.glassfish.grizzly.servlet.HttpServletRequestImpl.getRemoteHost(HttpServletRequestImpl.java:555)
	at javax.servlet.ServletRequestWrapper.getRemoteHost(ServletRequestWrapper.java:251)
	at org.spf4j.servlet.ExecutionContextFilter.logRequestEnd(ExecutionContextFilter.java:203)
	at org.spf4j.servlet.ExecutionContextFilter.doFilter(ExecutionContextFilter.java:137)
	at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:114)
```

this happens when running grizly-http 2.4.4 with jdk 11.0.2 in a docker container env

**Comment by technolion** [comment]
We are experiencing this as well. Any chance of fixing this?

**Comment by dabla** [comment]
We are also experiencing the same issue.

`2020-02-21 09:45:34,500 ERROR [grizzly-http-server-11] o.g.g.s.ServletHandler service exception:
javax.servlet.ServletException: javax.servlet.ServletException: javax.servlet.ServletException: javax.servlet.ServletException: java.io.IOException: Connection closed
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:116)
        at org.glassfish.grizzly.servlet.FilterChainImpl.invokeFilterChain(FilterChainImpl.java:83)
        at org.glassfish.grizzly.servlet.ServletHandler.doServletService(ServletHandler.java:202)
        at org.glassfish.grizzly.servlet.ServletHandler.service(ServletHandler.java:149)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: javax.servlet.ServletException: javax.servlet.ServletException: java.io.IOException: Connection closed
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:116)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:114)
        ... 7 common frames omitted
Caused by: javax.servlet.ServletException: javax.servlet.ServletException: java.io.IOException: Connection closed
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:116)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:114)
        ... 10 common frames omitted
Caused by: javax.servlet.ServletException: java.io.IOException: Connection closed
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:128)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:114)
        ... 13 common frames omitted
Caused by: java.io.IOException: Connection closed
        at org.glassfish.grizzly.asyncqueue.TaskQueue.onClose(TaskQueue.java:307)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.onClose(AbstractNIOAsyncQueueWriter.java:477)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.closeConnection(TCPNIOTransport.java:379)
        at org.glassfish.grizzly.nio.NIOConnection.doClose(NIOConnection.java:643)
        at org.glassfish.grizzly.nio.NIOConnection$6.run(NIOConnection.java:609)
        at org.glassfish.grizzly.nio.DefaultSelectorHandler.execute(DefaultSelectorHandler.java:213)
        at org.glassfish.grizzly.nio.NIOConnection.terminate0(NIOConnection.java:603)
        at org.glassfish.grizzly.nio.transport.TCPNIOConnection.terminate0(TCPNIOConnection.java:267)
        at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.writeCompositeRecord(TCPNIOAsyncQueueWriter.java:173)
        at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.write0(TCPNIOAsyncQueueWriter.java:68)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.processAsync(AbstractNIOAsyncQueueWriter.java:320)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:84)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.SameThreadIOStrategy.executeIoEvent(SameThreadIOStrategy.java:79)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.executeIoEvent(AbstractIOStrategy.java:66)
        at org.glassfish.grizzly.nio.SelectorRunner.iterateKeyEvents(SelectorRunner.java:391)
        at org.glassfish.grizzly.nio.SelectorRunner.iterateKeys(SelectorRunner.java:360)
        at org.glassfish.grizzly.nio.SelectorRunner.doSelect(SelectorRunner.java:324)
        at org.glassfish.grizzly.nio.SelectorRunner.run(SelectorRunner.java:255)
        ... 3 common frames omitted
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:468)
        at org.glassfish.grizzly.nio.transport.TCPNIOUtils.flushByteBuffer(TCPNIOUtils.java:125)
        at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.writeCompositeRecord(TCPNIOAsyncQueueWriter.java:165)
        ... 15 common frames omitted
2020-02-21 09:45:34,866 ERROR [grizzly-http-server-10] o.g.g.s.ServletHandler service exception:
javax.servlet.ServletException: javax.servlet.ServletException: javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:116)
        at org.glassfish.grizzly.servlet.FilterChainImpl.invokeFilterChain(FilterChainImpl.java:83)
        at org.glassfish.grizzly.servlet.ServletHandler.doServletService(ServletHandler.java:202)
        at org.glassfish.grizzly.servlet.ServletHandler.service(ServletHandler.java:149)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:116)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:114)
        ... 7 common frames omitted
Caused by: javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:116)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:114)
       ... 10 common frames omitted
Caused by: javax.servlet.ServletException: java.lang.NullPointerException
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:128)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:114)
        ... 13 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.glassfish.grizzly.http.HttpRequestPacket.remoteAddr(HttpRequestPacket.java:310)
        at org.glassfish.grizzly.http.HttpRequestPacket.getRemoteAddress(HttpRequestPacket.java:322)
        at org.glassfish.grizzly.http.server.Request.getRemoteAddr(Request.java:1219)
        at org.glassfish.grizzly.servlet.HttpServletRequestImpl.getRemoteAddr(HttpServletRequestImpl.java:540)
        at org.springframework.web.servlet.FrameworkServlet.publishRequestHandledEvent(FrameworkServlet.java:1143)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1023)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:124)
        ... 16 common frames omitted`
