### ISSUE TITLE
FilterChainContext.toString causes NullPointerException

### ISSUE THREAD

**Issue by scholzi100** [eclipse-ee4j/glassfish-grizzly#2110]
There is a bug with the toString method of FilterChainContext. This occurrs in the last milestone release 3.0.0-M1.

This issue seams to be strongly related to #1959.

```
09:02:53.599 [grizzly-nio-kernel(5) SelectorRunner] WARN  o.g.g.filterchain.DefaultFilterChain - GRIZZLY0013: Exception during FilterChain execution
java.lang.NullPointerException: Cannot read the array length because "value" is null
	at java.base/java.lang.String.<init>(String.java:269)
	at java.base/java.lang.String.valueOf(String.java:3381)
	at org.glassfish.grizzly.filterchain.FilterChainContext.toString(FilterChainContext.java:929)
	at java.base/java.text.MessageFormat.subformat(MessageFormat.java:1305)
	at java.base/java.text.MessageFormat.format(MessageFormat.java:886)
	at java.base/java.text.Format.format(Format.java:159)
	at java.base/java.text.MessageFormat.format(MessageFormat.java:861)
	at org.slf4j.bridge.SLF4JBridgeHandler.getMessageI18N(SLF4JBridgeHandler.java:265)
	at org.slf4j.bridge.SLF4JBridgeHandler.callLocationAwareLogger(SLF4JBridgeHandler.java:220)
	at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:303)
	at java.logging/java.util.logging.Logger.log(Logger.java:979)
	at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
	at java.logging/java.util.logging.Logger.log(Logger.java:1092)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:245)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:181)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:121)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:99)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	...
```

**Comment by scholzi100** [comment]
Close, fixed by https://github.com/eclipse-ee4j/grizzly/commit/d7a96f15083a55c38f63746007f664f1ede9f474
