### ISSUE TITLE
Grizzly 2.3.36-MULE-023 - HeapBuffer throwing IndexOutOfBoundsException

### ISSUE THREAD

**Issue by seeker25** [eclipse-ee4j/glassfish-grizzly#2152]
Grizzly is being used for Mule. 

Seem to be getting this exception, intermittently: 

Root Exception stack trace:
java.lang.IndexOutOfBoundsException
	at org.glassfish.grizzly.memory.HeapBuffer.get(HeapBuffer.java:357)
	at org.glassfish.grizzly.http.HttpCodecFilter.decodeHttpPacketFromBytes(HttpCodecFilter.java:818)
	at org.glassfish.grizzly.http.HttpCodecFilter.decodeHttpPacket(HttpCodecFilter.java:770)
	at org.glassfish.grizzly.http.HttpCodecFilter.handleRead(HttpCodecFilter.java:593)
	at org.glassfish.grizzly.http.HttpClientFilter.handleRead(HttpClientFilter.java:182)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:540)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)

Any suggestions? I couldn't find much by googling. 

Thank you.

**Comment by seeker25** [comment]
Related to a Mule build, upgraded from 2.3.36-MULE-023 to 2.3.36-MULE-024, seemed to fix this problem that would occur on PUTS and POSTS when they use 100-continue.
