### ISSUE TITLE
Out of memory caused by TrimmableHeapBuffer

### ISSUE THREAD

**Issue by juanwippel** [eclipse-ee4j/glassfish-grizzly#2176]
I am facing Out Of Memory issues on Glassfish 4.0 (Build 89) server.

Version of grizzly from \glassfish\glassfish\modules\nucleus-grizzly-all.jar is
version="2.3.1"

Whenever I face this issue, there is always at-least one thread with following dump:

"http-listener-2(18)" - Thread t@20756
   java.lang.Thread.State: RUNNABLE
	at java.nio.ByteBuffer.wrap(ByteBuffer.java:373)
	at java.nio.ByteBuffer.wrap(ByteBuffer.java:396)
	at org.glassfish.grizzly.memory.HeapBuffer.toByteBuffer0(HeapBuffer.java:1008)
	at org.glassfish.grizzly.memory.HeapBuffer.toByteBuffer(HeapBuffer.java:874)
	at org.glassfish.grizzly.memory.HeapBuffer.toByteBuffer(HeapBuffer.java:866)
	at org.glassfish.grizzly.ssl.SSLConnectionContext.unwrap(SSLConnectionContext.java:172)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.unwrapAll(SSLBaseFilter.java:353)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.handleRead(SSLBaseFilter.java:252)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:288)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:206)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:136)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:114)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:838)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:113)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:115)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:55)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:135)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:564)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:544)
	at java.lang.Thread.run(Thread.java:748)

This happening too much times per day

![image](https://user-images.githubusercontent.com/47954346/196519394-65a4798b-2f0f-41eb-91b4-c8e50f4df0fc.png)

**Comment by mnriem** [comment]
Can you supply a reproducer?
