### ISSUE TITLE
NPE when closing OutputBuffer

### ISSUE THREAD

**Issue by MarcelMerkle** [eclipse-ee4j/glassfish-grizzly#2214]
Hi,

we experienced an issue when trying to resume an asynchronous response in our HTTP server. The issue was caused by an NPE that was thrown when trying to close the `OutputBuffer`:

```
java.lang.NullPointerException: Cannot invoke "org.glassfish.grizzly.http.HttpContext.getOutputSink()" because "this.httpContext" is null
        at org.glassfish.grizzly.http.io.OutputBuffer.blockAfterWriteIfNeeded(OutputBuffer.java:906)
        at org.glassfish.grizzly.http.io.OutputBuffer.close(OutputBuffer.java:684)
        at org.glassfish.grizzly.http.server.NIOOutputStreamImpl.close(NIOOutputStreamImpl.java:76)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:251)
        at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:565)
        at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:403)
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:763)
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:398)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:388)
        at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:926)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
        at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:963)
        at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:914)
```
We are using grizzly-http-server version 4.0.2.

This is the first time we saw such an issue although we are using this version for several months now.

Best regards,
Marcel

**Comment by carryel** [comment]
This issue is similar to https://github.com/eclipse-ee4j/glassfish-grizzly/issues/2228.
It appears to be caused by the ServerOutputBuffer being recycled during HttpServerFilter's afterService() process, and then another thread is referencing that OutputBuffer and executing specific logic concurrently. I'll look into the issue above and see if I can improve this as well.

**Comment by carryel** [comment]
Although I don't know the exact reproducible scenario and haven't looked closely at how Jersey integrates with Grizzly's Response resume, I submitted a PR that briefly improves the situation when resume and OutputBuffer close are called concurrently, referring to the error trace.

**Comment by carryel** [comment]
This issue may have been fixed with https://github.com/eclipse-ee4j/glassfish-grizzly/pull/2240.

This will be included in the next release.

If you encounter any further issues or problems in the future, please let me know.

**Comment by MarcelMerkle** [comment]
@carryel Thank you so much for the fix! I will let you know if we observe similar issues with the new version.

**Comment by MarcelMerkle** [comment]
@carryel Do you have any idea when the next release will be published?

**Comment by carryel** [comment]
@MarcelMerkle I don't know the exact timing, but I think it will be soon. There were changes to CI and Maven Central that affected the release, but I saw Glassfish 7.1.0 released recently, and I believe Grizzly can be released based on that process.

I will also keep an eye on the Grizzly release.

**Comment by carryel** [comment]
@MarcelMerkle If you have any thoughts on this https://github.com/eclipse-ee4j/glassfish-grizzly/issues/2231#issuecomment-3743792939, could you please share your thoughts?

**Comment by MarcelMerkle** [comment]
> [@MarcelMerkle](https://github.com/MarcelMerkle) If you have any thoughts on this [#2231 (comment)](https://github.com/eclipse-ee4j/glassfish-grizzly/issues/2231#issuecomment-3743792939), could you please share your thoughts?

We are currently on Java 17 and plan to go to Java 21 later this year. So if this fix would go to 5.0.0 only, we could not adapt it right away.
